### ISSUE TITLE
restaurer l'item selectionné a la creation de l'acitivité

### ISSUE THREAD

**Issue by LucasBettarel** [24HeuresINSA/24h-android-app#111]
references de #68

**Comment by remipichon** [comment]
Je comprends pas ta issue. Il faut que j'implémente le cleared des choices au changement d'activité ou bien que c'est ce qu'il se passe et il faut que je prévienne se comportement

**Comment by LucasBettarel** [comment]
Pardon, lorsque l'on clique sur une category du drawer qui nous fait changer d'activité, il n'y a plus d'item sélectionné: je n'ai pas réussi a résoudre ce problème.

En revanche, lorsqu'on clique sur une categorie de la meme activité on a bien l'item courant selectionné en rouvrant le drawer.

Cela est indépendant (quoique lié) a la #68. En effet, au changement d'activité, l'item selectionné n'est plus bleu, mais pas non plus background_grey. (cette dernière propriété étant gérée dans les layouts)

C;est mieux?

**Comment by remipichon** [comment]
Je vois, je renomme la tache

**Comment by LucasBettarel** [comment]
Apres test sur la nouvelle version, ca ne le fait plus systématiquement, mais ça arrive dans les cas suivants : 

NightActivity -> Static Activity
Day Activity - > Static Activity

**Comment by remipichon** [comment]
Oui, je viens de voir. C'est juste StaticActivity qui restaure pas l'item selected. Si tu veux je regarde ce bout de code avant de valider ta merge request pour tout embarqué d'un coup

**Comment by remipichon** [comment]
a voir avec Billon comment faire ca proprement
