### ISSUE TITLE
set selected category on drawer -> dayActivity

### ISSUE THREAD

**Issue by LucasBettarel** [24HeuresINSA/24h-android-app#112]
reference #68 

Dans DrawerCategoriesClickListener de Day Activity  (qui devrait lancer la methode -> met en bleu les categories sélectionnées, en gris les autres), je n'arrive pas a faire le lien entre la item sélectionnée et le category adapter (qui a accès au views de la categoriesList).

Dans mes différents essais, soit ça ne fait rien du tout, soit ça ne change que la première category (divertissment), et encore, mal...

Quelques questions du coup:
- quand est appelée la methode getView de category adapter : a chaque clique d'un item de cette liste dans le drawer; a chaque arrivée dans Day Activity, a chaque ouverture de l'appli?
- la solution a mon probleme se trouve peut etre dans la methode selectcategory de DayActivity? Comment acceder aux views ici alors?
- ...

Merci bien! (il me manque un peu de concepts la aussi!)

**Comment by remipichon** [comment]
C'est pas déja le cas ?

**Comment by remipichon** [comment]
quand est appelée la methode getView de category adapter : a chaque clique d'un item de cette liste dans le drawer; a chaque arrivée dans Day Activity, a chaque ouverture de l'appli?

CategoryAdapter.getView est appelé à chaque fois qu'apparait la navigationDrawer. Il faut eviter de faire trop de choses dedans.


la solution a mon probleme se trouve peut etre dans la methode selectcategory de DayActivity? Comment acceder aux views ici alors?
DayAcitivy.selectCategory ne sert qu'a envoyer l'evenement a destination des fragments pour filtrer la liste ou la maps.

**Comment by LucasBettarel** [comment]
Ok, donc il s'agit de faire un if selected->blue else grey dans le get view
de category adapter.
Actuellement on affecte des icone a chaque ouverture du drawer, c'est pas
un peu lourd du coup?

et dans ce cas, quel est la maniere la plus propre de recuperer la liste
des categories selectionnées(si plusieurs) dans cet adapter ?



Lucas Bettarel

**Comment by remipichon** [comment]
c'est ca

pas grave pour les icones, c'est ainsi

c'est la maniere conventionnelle qu'on a la

**Comment by remipichon** [comment]
#113 clot cette issue ?

**Comment by LucasBettarel** [comment]
non, regarde le comment que j'ai mis sur [RPI] clean code
Je suis pas sur que le getView de category adapter se lance a chaque ouverture du drawer, comme tu disais plus haut.

Qu'en penses tu?

**Comment by remipichon** [comment]
Cette méthode ne marche pas du coup :) 

Ce qui ne fonctionne pas c'est ce que j'ai fais pour passer activity.getPositionSelected OU la tambouille que j'ai faite avec les super() sur les onEvent ?

**Comment by remipichon** [comment]
Hey, mais j'ai commit ca ! C'est meme en prod !
