### ISSUE TITLE
Set Sort Icon from list in action bar item only on day activity

### ISSUE THREAD

**Issue by LucasBettarel** [24HeuresINSA/24h-android-app#114]
si il n'y en a plus qu'une, inutile de surcharger l'ecran de la liste

tester sur les petites devices pour voir si ca passe avec le titre, quitte a mettre seulement "animations" plutot que "Liste des animations"

**Comment by remipichon** [comment]
pas à faire, dans l'idée il faut que je fasse le tri par location
