### ISSUE TITLE
Snack Bar "Rien a afficher pour le moment" se déclenche trop tot á l'ouverture de l'appli

### ISSUE THREAD

**Issue by LucasBettarel** [24HeuresINSA/24h-android-app#115]
meme si il y a effectivement des ressources

**Comment by remipichon** [comment]
Tu peux etre plus précis ? Est ce que ca le fait encore avec la 0.3.1

**Comment by LucasBettarel** [comment]
Quand on lance l'appli et que les donnees ne sont pas encore telechargees,
le message s'affiche. c'est penible parce qu'on croit que ca bug alors que
ca charge. ca le fait aussi sur la 031.



Lucas Bettarel

2015-04-28 18:29 GMT+08:00 Remi Pichon <notifications@github.com>:

**Comment by remipichon** [comment]
C'est juste celui la de SnackBar ? Je crois que ca vient de la Maps qui est init sans données

Est ce tu as remarqué que  d'autres SnackBar ont un comportement non intuitif ?

**Comment by LucasBettarel** [comment]
Je crois oui, le reste m'a pas choque pour l'instant



Lucas Bettarel

**Comment by remipichon** [comment]
Ca peut rester en minor ?



--
Remi Pichon

**Comment by LucasBettarel** [comment]
oui oui bien sur



Lucas Bettarel
