### ISSUE TITLE
Notification Icon

### ISSUE THREAD

**Issue by lbillon** [24HeuresINSA/24h-android-app#117]
![screenclip](https://cloud.githubusercontent.com/assets/420931/7338128/318ff20a-ec42-11e4-9a0b-b2d5811d0418.png)

Pour l'instant on a une petite cloche, on aurait pas un logo 24 blanc qui traine quelque part @LucasBettarel ?

**Comment by LucasBettarel** [comment]
je t'en fais un demain si tu veux, la je vais aller dormir :)



Lucas Bettarel

2015-04-27 0:30 GMT+08:00 Laurent BILLON <notifications@github.com>:

**Comment by LucasBettarel** [comment]
Voici quelques exemples, dis moi ce que tu en penses

Il faut faire attention a la lisibilite, comme l'icone est tres petite, je
sais pas si les lettres rendent bien. On peut trouver une autre idee si
c'est nul.



Lucas Bettarel

**Comment by LucasBettarel** [comment]
Tu as recu mes icones sur gmail?

**Comment by lbillon** [comment]
Oui c'est nickel !

Laurent.

--
Laurent BILLON
06 32 57 58 24
