### ISSUE TITLE
recuperation données via port 80

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#122]
Le port 3030 est bloqué sur le réseau INSA

Que proposes tu pour pouvoir rendre dispo les données via un port HTTP ?

**Comment by thelittle** [comment]
Je propose de publier sur le port 80. Mais pour cela, il faut que je migre
Assomaker sur un autre serveur.
Ce sera fait le week-end prochain (pas avant, je risque d'être pris par les
préventes et la soutenance pour la subvention de la mairie de Villeurbanne).

Léo MARTINEZ

2015-04-27 8:23 GMT+02:00 Remi Pichon <notifications@github.com>:

**Comment by remipichon** [comment]
Excellent, ci c'est pret pour la 4eme MEP du 4 mai je valide !

**Comment by thelittle** [comment]
Yep ce sera le cas. ;)

Léo MARTINEZ

2015-04-27 8:27 GMT+02:00 Remi Pichon <notifications@github.com>:

**Comment by lbillon** [comment]
Migrer assomaker sur un autre serveur ?
A mon avis on va pouvoir s'en sortir avec un virtualhost (ServerBlock)
=> http://www.nginxtips.com/nginx-virtual-hosts-server-blocks/

**Comment by thelittle** [comment]
J'ai peur que ça fasse merder le SSL...

**Comment by lbillon** [comment]
Ah, peut-être .. Je te laisse gérer ; )

Laurent.

--
Laurent BILLON
06 32 57 58 24


2015-04-30 21:00 GMT+02:00 Léo Martinez <notifications@github.com>:

**Comment by thelittle** [comment]
Je viens de terminer la migration d'assomaker (ça va plus vite maintenant ! :p)
Du coup, l'URL mobile.24heures.org publie désormais à la fois sur les ports 3030 et 80. Si le port 80 ne fonctionne pas ou ne renvoie pas un JSON, c'est que la réplication des DNS est en cours (attendre quelques heures). A terme, (c'est à dire après la prochaine MEP), je couperai le port 3030.

Attention toutefois, test.mobile.24heures.org n'a pas été migré, donc le port 80 n'est pas fonctionnel pour les tests (il faudra rester sur du 3030). Le port 80 ne concerne que la prod.

**Comment by remipichon** [comment]
Excellent !

L'appli partira en prod avec le port 80 c'est parfait !
