### ISSUE TITLE
Implémentation GCM Côté serveur

### ISSUE THREAD

**Issue by lbillon** [24HeuresINSA/24h-android-app#131]
Du coup, voilà une ébauche du code côté serveur, je n'ai pas d'assomaker de débug pour tester, peux-tu essayer d'intégrer ça ? : 

https://gist.github.com/lbillon/6857c053e80bb9b4da47

Merci beaucoup !

N'hésite pas si tu as des questions : )

**Comment by martinezleoml** [comment]
Je pense que tout est bon. ;)
