### ISSUE TITLE
static page : Tickets

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#132]
Détail des prix :
En ligne
1 soir : 10€ (+0,99€ de frais de location)
2 soirs : 16€ (+0,99€ de frais de location)
Sur place
1 soir : 15€
2 soirs : 25€
Et bien sûr, un lien qui mène vers la page https://www.24heures.org/billetterie pour que les gens puissent acheter leur place.
On peut mettre que l'accès à la zone se fera à partir de 19h45.
Un petit détail, l'accès à la zone concert c'est jusqu'à 2h et non pas 2h15

![screen-billetterie](https://cloud.githubusercontent.com/assets/3901946/7357761/1fb89ace-ed31-11e4-9a9e-e83b86048a02.png)

**Comment by remipichon** [comment]
Je m'en occupe

**Comment by LucasBettarel** [comment]
Le design du statique ? Si tu t'ennuie tu peux plutot me faire des tabs
pour la nuits? (vendredi/samedi)



Lucas Bettarel

2015-04-29 22:45 GMT+08:00 Remi Pichon <notifications@github.com>:

**Comment by remipichon** [comment]
Il reste a rendre beau la page, feel free de poutrer completement mon boulot

**Comment by LucasBettarel** [comment]
![2015-04-29 17 03 31](https://cloud.githubusercontent.com/assets/11612891/7396602/00e16298-eed5-11e4-9755-1a36cf8c4f2d.png)

dis moi ce que tu en penses?

**Comment by remipichon** [comment]
Excellent ! J'ai bien fait de te laisser le faire !




--
Remi Pichon


2015-04-29 19:06 GMT+02:00 LucasBettarel <notifications@github.com>:

**Comment by remipichon** [comment]
Hesite pas à fermer tes issues une fois terminée (ca fait tellement plaisir de voir que le nombre diminue)

**Comment by LucasBettarel** [comment]
Je viens de me rendre compte qu'il faut que j'ajoute un sliding layout pour
le mode paysage

de plus, un probleme pour toi : il faut eviter le multiple click sur le
bouton, qui crash l'app et ouvre plusieurs page web!

Ah ah bonne chance!



Lucas Bettarel

2015-04-30 16:25 GMT+08:00 Remi Pichon <notifications@github.com>:

**Comment by LucasBettarel** [comment]
@remipichon

**Comment by remipichon** [comment]
Ho oui la scrollView. J'y ai pensé en plus quand j'ai commencé. 

Je m'occupe du multipleClick
