### ISSUE TITLE
Click on liveupdate notification should open notifications list

### ISSUE THREAD

**Issue by lbillon** [24HeuresINSA/24h-android-app#138]
Lorsque je clique sur une notification, je suis actuellement amené à la page principale, on devrait être amené au fragment affichant la liste des updates.

Je ne comprend pas trop comment a été codée le système de seitchage de fragment (il semble que l'on soit obligé de cliquer sur le drawer pour changer de fragment), @remipichon  peux-tu jeter un oeil ?

Pour info, l'intent de la modification est générée ici : 
https://github.com/24HeuresINSA/24h-android-app/blob/develop/app/src/main/java/com/insalyon/les24heures/androidService/NotificationService.java#L70

**Comment by remipichon** [comment]
J'ai commit le code, mais j'ai pas testé (bhouuuuuu c'est mal) 
Je sais pas trop comment bouchonner ce traitement, tu peux me dire si c'est OK ?

**Comment by lbillon** [comment]
Fixed
