### ISSUE TITLE
Application closes when selecting another Static Activity in the navigation drawer

### ISSUE THREAD

**Issue by lbillon** [24HeuresINSA/24h-android-app#139]
Steps to reproduce :
* Navigate to a static activity fragment
* Select a static activity fragment in the notification drawer

The application closes unexpectedely.

**Comment by remipichon** [comment]
En fait c'est pas un crash, c'est que je fais un finish sur l'activity sans en demarrer une autre. J'ai fais un quick fix sur la develop 

A l'occasion j'aimerais bien qu'on regarde le métier qui switch les fragments statiques.

**Comment by lbillon** [comment]
"A l'occasion j'aimerais bien qu'on regarde le métier qui switch les
fragments statiques."

Oui !

Même, ça pourrait être marrant de se faire un point vidéo avec tout le
monde ?
Ne serais-ce que pour se voir en équipe, et lancer la 4e MEP

En faisant un petit ordre du jour ça devrait pas être trop long !

++

Laurent.

Laurent.

--
Laurent BILLON
06 32 57 58 24

**Comment by remipichon** [comment]
Je prepare ca pour dimanche apres midi

**Comment by LucasBettarel** [comment]
Dimanche aprem (soir) c'est bon pour moi. Avant 18h si possible.
Revoir ta gueule Laurent ! ça va me faire marrer!



Lucas Bettarel

2015-04-29 20:51 GMT+08:00 Remi Pichon <notifications@github.com>:

**Comment by lbillon** [comment]
@LucasBettarel, moi aussi !
Envoies nous une invitation google agenda : )

Laurent.

--
Laurent BILLON
06 32 57 58 24


2015-04-29 16:26 GMT+02:00 LucasBettarel <notifications@github.com>:
