### ISSUE TITLE
backend : tout le temps envoyer le jour pour les artistes

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#150]
Nous avons du jour coté mobile pour savoir ou afficher l'artiste
Le jour mais pas l'horaire jusqu'au jour de la manif, puis le jour et l'horaire le soir de la manif

**Comment by remipichon** [comment]
comment est pris en compte le boolean d'envoie des horaires ?

**Comment by thelittle** [comment]
Si ça vaut 1, tout est publié, si ça vaut 0, alors on publiera que le jour.
Je ferai la modif Assomaker dans la semaine (j'ai moultimoult trucs sur le
feu !)

Léo MARTINEZ

2015-05-05 1:37 GMT+02:00 Remi Pichon <notifications@github.com>:

**Comment by remipichon** [comment]
ma question était pas claire : est ce que le JSON est regénéré lorsqu'on change le boolean ?

**Comment by remipichon** [comment]
J'ai ma réponse. Je bosse avec un JSON local, des que le nouveau export l'appli sera en mesure de le prendre en charge.

**Comment by thelittle** [comment]
Oui le JSON est régénéré.

Léo MARTINEZ

2015-05-05 12:36 GMT+02:00 Remi Pichon <notifications@github.com>:
