### ISSUE TITLE
facilities - lieux utiles : creer nouvelles ressources

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#155]
LIEUX UTILES

Entrée/sortie  (45.78323928888201, 4.87698420882225)

Toilettes :
	- entrée (45.78343943255239, 4.877571612596512)
	- gymnase C (45.78456920203871, 4.877198785543442)
	- MdE (45.784125901178214, 4.8748089373111725)

Stand Accueil (45.783536698375755, 4.877375811338425)

Poste de secours (45.784350357750675, 4.8772551119327545)

Stand prévention (45.78340202257514, 4.877257794141769)

3 passages courses

bar - bouffe (45.783905184667354, 4.876957386732101)

**Comment by LucasBettarel** [comment]
Je provide les icones later in the week (after 0.9)

**Comment by remipichon** [comment]
Ca me va, je m'attaque à ca vendredi au plus tard. Livraison estimée vendredi soir
