### ISSUE TITLE
icon design

### ISSUE THREAD

**Issue by LucasBettarel** [24HeuresINSA/24h-android-app#163]
DONE - markers facilities:
       - entree-sortie :use icon ic_exit.png
       - toilettes : use icon ic_toilets.png
       - secours : use icon ic_secours.png
       - accueil : use icon ic_home.png
       - prevention  : use icon prevention_gris.png
       - passage course : use icon ic_crossing.png
       - bar : use icon ic_beer.png
       - bouffe : use icon ic_food.png
DONE - grande scene badge
DONE - petite scene badge
DONE- ALL : foncer (blue+black)
DONE - entrance : use icon billeterie.png

**Comment by LucasBettarel** [comment]
@remipichon 

DONE - markers facilities:
       - entree-sortie :use icon ic_exit.png
       - toilettes : use icon ic_toilets.png
       - secours : use icon ic_secours.png
       - accueil : use icon ic_home.png
       - prevention  : use icon prevention_gris.png
       - passage course : use icon ic_crossing.png
       - bar : use icon ic_beer.png
       - bouffe : use icon ic_food.png

**Comment by remipichon** [comment]
Nouveau icone : 

* entrée
* stand prévention (SIDA et SAM)
* espace VIP

**Comment by remipichon** [comment]
besoin icon
* SAM (la petite tete ronde ?)

**Comment by LucasBettarel** [comment]
fini.
dans drawable 
marker_####
en 32x32
