### ISSUE TITLE
Backend concert

### ISSUE THREAD

**Issue by LucasBettarel** [24HeuresINSA/24h-android-app#165]
-> Image ne marche pas : De Hofnar, Erotic Market
-> Image principale mal cadree : The Subways, Yuksek

-> Pour tous : rajouter des images (paysage) sur le backend
-> Modifier l'ordre et mettre par importance

(plus tard : horaire)

**Comment by remipichon** [comment]
restant 
-> Image ne marche pas : De Hofnar, Erotic Market
-> Image principale mal cadree : The Subways, Yuksek

probleme : 
backend envoie pas les images secondaires des artistes

**Comment by LucasBettarel** [comment]
COOL ! c'est beau!

En fait il ne reste plus que l'image de Erotic Market qui marche pas (chez moi en tout cas)
le cadrage est bon maintenant.

toujours pas d'images secondaires c'est vrai.
