### ISSUE TITLE
Remove position collaspe du detail fragment on list DAY+NIGHT

### ISSUE THREAD

**Issue by LucasBettarel** [24HeuresINSA/24h-android-app#166]
Je sais pas si c'est deja ailleurs, je te le mets ici au cas ou pour pas oublier

**Comment by remipichon** [comment]
Heu bha non "anchored" il faut le laisser sinon on peut pas voir la main_picture

**Comment by LucasBettarel** [comment]
pardon je sais jamais, je parle de quand c'est en petit en bas.

**Comment by remipichon** [comment]
c'est le mode "collaspe"

Il doit pas manquer grand chose, je regarde ca pour la 1.0
