### ISSUE TITLE
Navigation drawer on rotate

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#169]
si on rotate lorsque le navigation drawer est open, le appName n'a pas la fleche de retour et le social sharing est present

**Comment by lbillon** [comment]
Corrigé pour le social sharing ( 4d4b133ec80d444d9acaeab01a1187ab8d83f086 ), @remipichon , je te laisse regarder pour le appName.

**Comment by remipichon** [comment]
ca marche

**Comment by remipichon** [comment]
7c911b65544b4dcea73429fa8766e0a3bb9cd790 fixed it
