### ISSUE TITLE
nuit detail : background tint

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#173]
background tint is only used in api 21

**Comment by remipichon** [comment]
J'ai essayé d'utiliser des viewCompat mais sans succes. Peux tu generer l'icone avec la couleur qu'il faut directement ? On verra comment faire mieux plus tard

**Comment by LucasBettarel** [comment]
Ah oui ok, j'ai oublie ca mais je m'en occupe pour la 1.0

j'ai une derniere grosse passe a faire sur les icones en photoshop.



Lucas Bettarel
