### ISSUE TITLE
Set init drawer icon : ALL

### ISSUE THREAD

**Issue by LucasBettarel** [24HeuresINSA/24h-android-app#176]

**Comment by remipichon** [comment]
c'est a dire ?

**Comment by LucasBettarel** [comment]
Actuellement, quand on launch l'appli et qu'on ouvre le drawer, "se devertir" est sélectionné, alors que la map display toutes les ressources.

il faut soit sélectionner "Tout" en valeur initiale, soit rien du tout, au choix.

2 choses a gerer : 
- l'etat item selected (background gris)
- le setSelectedCategoryInit (icon et text bleu)

Ca se passe de la l.57 à 79 de Day activity, et l.84 de categoryadapter

La ou j'arrive pas, c'est d'executer du code uniquement au lauch est plus apres (etat init, avec moi il se reinitialise a chaque arrivee dans dayactivity).

Pour selectionner "Tout" je pense qu'il faut poser en dur positionInit = position(tout) (dans l'idée)

plus de details?

**Comment by remipichon** [comment]
Je m'en occupe, c'est clairement de la regression. Je vais voir ce qui est cassé
