### ISSUE TITLE
taille du view tab du view pager

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#178]

**Comment by LucasBettarel** [comment]
c'est quoi ça?
tu veux que ça soit plus large (height) ? je l'avais diminué on purpose, parce que plus joli, mais cest vrai que j'ai pas testé sur des petits ecrans

**Comment by remipichon** [comment]
Je crains le missclick

**Comment by remipichon** [comment]
Je regarde sur des petits ecrans a grande resolution, au besoin je ferai un "vote" ce weekend

**Comment by LucasBettarel** [comment]
t'embete je rajoute 5dp



Lucas Bettarel

**Comment by LucasBettarel** [comment]
*pas



Lucas Bettarel

**Comment by remipichon** [comment]
ok




--
Remi Pichon
