### ISSUE TITLE
notification icon

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#193]
il est bien trop gros

si tu ajoutes une resource en favoris, la notif arrive en 14 secondes

**Comment by LucasBettarel** [comment]
tu veux dire le poids/taille de l'image?

**Comment by remipichon** [comment]
taille uniquement, sur la notifcation on ne voit qu'une partie de l'icone

**Comment by LucasBettarel** [comment]
![2015-05-09 09 13 57](https://cloud.githubusercontent.com/assets/11612891/7549592/da3a8eca-f66e-11e4-8629-9ab586c538bb.png)

ah bon? pas chez moi... je reduis de combien alors?

**Comment by remipichon** [comment]
ouvre le panneau de notifcation, c'est dans la notif que licone est trop
gros




--
Remi Pichon


2015-05-09 11:18 GMT+02:00 LucasBettarel <notifications@github.com>:
