### ISSUE TITLE
UC 1.1.5 En tant que festivaliers j’ai accès à une carte, les resources sont identifiées par une couleur par categories

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#22]

**Comment by LucasBettarel** [comment]
on peut mettre des points a la place des marqueurs? Sinon on peut differencier le marqueur sur lequel on vient de cliquer (qui reviendrait en icone pointe)
pour les couleurs, tu peux te baser sur les couleurs des categories? (je peux te donner les codes si tu les a pas

**Comment by remipichon** [comment]
Alors oui pour les points, c'etait le but mais il me faut les drawable de chaque couleur. 

Pour les couleurs je peux me baser sur celles des categories mais il me le code RGB. En effet, en l'état j'utilise le default marker (celui bien connu de Maps) dont il est possible de configurer la couleur uniquement. Si on garde la l'idée d'utiliser des petits ronds il me faut les bons drawables. J'ai pas réussi à les trouver sur internet. 
http://fr.wikipedia.org/wiki/Teinte_Saturation_Valeur

Le blue_hazure que j'ai mis pour identifier le selected est nul, si on met le red par defaut ca se voit bien. Dans l'ideal je prefereai utiliser les petits ronds mais il me faut les drawables.

**Comment by LucasBettarel** [comment]
je te fais ca demain



Lucas Bettarel

**Comment by remipichon** [comment]
Excellent
