### ISSUE TITLE
UC 1.1.3 En tant que festivaliers je peux filtrer ce qui est affiché sur la carte en fonction de “maintenant” ou de “tout ce qu’il reste à venir“

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#23]

**Comment by remipichon** [comment]
ajouter une SpecificCategory utiliser par isDisplayable

ScheduleService.getNextSchedules  => if empty not displayable
ScheduleService.getNextSchedule

utiliser un mock pour la date dans ScheduleService

**Comment by remipichon** [comment]
ne retourne que les resources de la journée en cours ?

**Comment by remipichon** [comment]
Lucas, tu pourrais me fournir un icone pour le navigation drawer ?

**Comment by LucasBettarel** [comment]
l'icone est dans le commit de design : "icon UC 1.1.3" : ic_now et ic_now_bleu (m/h/xhdpi)

**Comment by remipichon** [comment]
Excellent !
