### ISSUE TITLE
Hors facilities UC 1.5.3 En tant que festivaliers je suis averti 15 minutes avant le début de animations que j’ai en favoris

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#24]

**Comment by lbillon** [comment]
Ok pour les groupes, pour les animations par contre, ça risque pas d'être un peu spammant ?

**Comment by LucasBettarel** [comment]
Je pense pas qu'ils vont s'amuser a liker toutes les anims. Si c'est le cas
ils l'auuront cherché non?



Lucas Bettarel

2015-04-26 23:14 GMT+08:00 Laurent BILLON <notifications@github.com>:

**Comment by remipichon** [comment]
+1 Lucas

On notifie que les ressources en fav

**Comment by lbillon** [comment]
Oui, ce qu'il me faisait peur c'est que certaines anims ont 3/4 plages
horaires différentes

Laurent.

--
Laurent BILLON
06 32 57 58 24

**Comment by lbillon** [comment]
#188
