### ISSUE TITLE
UC 2.7.1 En tant que festivaliers je peux connaître la carte de chaque consommable : bière et bouffe

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#26]

**Comment by LucasBettarel** [comment]
je rajoute une ligne "carte des conso" dans le menu

**Comment by LucasBettarel** [comment]
d'ailleurs pour chaque page statique, je cree une activity ou un fragment de day activity?
faudra juste que tu me brief rapidement la dessus, que je perde pas de temps a faire de la merde.

**Comment by remipichon** [comment]
Ha oui, c'est dans ma road map pour la 3eme MEP. 

Pour le moment il y a DayActivity et NightActivity qui heritent toutes deux de BaseDynamicDataActivity. BaseDynamicDataActivity gere le NavigationDrawer, toute l'action bar (search et favorites) ainsi que la recuperation et le stockage des données. 
Je vais modifier cette archi pour que tu puisses faire le pages statiques. Il y a aura une abstract BaseDynamicDataActivity et une class BaseStaticDataActivity qui hériteront de BaseActivity.
BaseStaticDataActivity s'occupera des pages statiques, de toutes les pages statiques meme Billeterie qui est specific à la nuit

**Comment by remipichon** [comment]
voilà, #74 est terminée et est sur master

**Comment by remipichon** [comment]
Restant : utiliser les vraies images (attendre les bars)

**Comment by remipichon** [comment]
pour les bieres, le titre est trop grand et n'est pas lisibile (le faire glisser comme sur la DayList) et on voit pas tout le détail => passer ca en wrap_content pour que ca prenne plusieurs lignes ? 

les bars et la bouff ont envoyé les photos


@LucasBettarel  tu es sur le coup ?

**Comment by LucasBettarel** [comment]
en ce moment meme tres cher



Lucas Bettarel
