### ISSUE TITLE
application version

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#34]
faire comme pour data version
bloquant.minor

bloquant empeche la recuperation des données et propose avec instance de mettre a jour a chaque restart et regulierement
minor propose de mettre a jour a chaque restart

**Comment by remipichon** [comment]
Coté backend :
stockage de l'information
envoi de l'information au moyen d'un nouveau verbe qui ne renvoie que l'application version 
mise à disposition d'un verbe pour mettre à jour l'application version en POST (pas besoin de back office)
Coté application
dès le démarrage, le plus tôt possible, le get de l'application version est effectué
à sa réception, l'application version est comparée à celle de l'application
si major change : 
les données ne sont pas mises à jour, si pas de données en local, pas de données
une popup s'affiche toutes les 10 secondes avec un lien pour mettre à jour
si minor change :
une popup annonce avec un lien proposant de mettre à jour

**Comment by remipichon** [comment]
L'idée est tout simple : informer l'utilisateur de nos mises à jour + le forcer à mettre à jour 

Pour cela nous allons utiliser une donnée application-version sur deux entier : major.minor. 

Coté backend :
* stockage de l'information
* envoi de l'information au moyen d'un nouveau verbe qui ne renvoie que l'application version 
mise à disposition d'un verbe pour mettre à jour l'application version en POST (pas besoin de back office)

Coté application
* dès le démarrage, le plus tôt possible, le get de l'application version est effectué
à sa réception, l'application version est comparée à celle de l'application
* si major change : 
* * les données ne sont pas mises à jour, si pas de données en local, pas de données
* * une popup s'affiche toutes les 10 secondes avec un lien pour mettre à jour
* si minor change :
* * une popup annonce avec un lien proposant de mettre à jour

Que pensez vous de cela ? 

Leo, je pense qu'utiliser un autre verbe n'est pas un mauvaise idée car l'idée est de faire cette vérification le plus tôt possible et pour des raisons techniques la recuperation des ressources n'est effectuée dès le démarrage.

**Comment by thelittle** [comment]
Je préfèrerais que l'appli fasse appel à une page spécifique plutôt qu'envoyer un verbe POST. Parce qu'il n'y a pas de logique applicative sur le serveur qui sert les JSON pour l'appli mobile.

Du coup, une page /get-version t'irait ?
Précise-moi le format de la réponse.

**Comment by nicondsc** [comment]
Kiki m'avait assigné à cette issue au départ mais honnêtement je n'ai
aucune idée de comment faire, je pense qu'il sera beaucoup plus à même de
le faire (et ça lui prendra sans doute moins de temps que si il doit
m'expliquer).
​

**Comment by remipichon** [comment]
Je me suis fourvoyé, bien sur qu'un /get-version irait très bien. Le POST est plutot un PUT ou un PATCH enfin n'importe quoi qui permette de faire un UPDATE sur la version de l'application. 
Par mesure de sécurité, pourrais tu exiger les droits super admin sur le backend pour autoriser la mise à jour de la version ?

Pour le format de la réponse au /get-version : 

android : 'major.minor'

(un jour il y aura une version iOs !)

**Comment by remipichon** [comment]
Le slashscreen instancie le singleton de check app version qui effectue la comparaison et envoie un event à destination de BaseActivity

a la reception de l'event, BaseActivity lance le dowload eventuelle des données (desormais le sharedPref n'est plus null)
affiche la popup minor changes
lance le timerTask pour la popup major changes

le singleton check app version stocke l'autorisation de download dans les sharedPref

BaseActivity lance au onStart le download des donnees qui check le sharedPref pour savoir s'il faut autoriser le download (true) ou pas (false) ou attendre l'event = un false (null)
BaseActivity check au onStart le localPref, si dowload à false, lance le timerTask pour la popup major changes

**Comment by thelittle** [comment]
C'est en prod ! ;)

**Comment by remipichon** [comment]
Ca ne répond pas chez moi

http://mobile.24heures.org:3030/version

**Comment by thelittle** [comment]
Chez toi doit avoir un problème alors...
Fonctionne en Wi-Fi (Free) et 3G (Bouygues).

**Comment by remipichon** [comment]
Depuis le réseau de l'INSA ca sort pas, un soucis de proxy ? Je code ca ce soir depuis chez moi

**Comment by thelittle** [comment]
Un blocage de port, pas étonnant à l'insa...

Le lundi 13 avril 2015, Remi Pichon <notifications@github.com> a écrit :

> Depuis le réseau de l'INSA ca sort pas, un soucis de proxy ? Je code ca ce
> soir depuis chez moi
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/24HeuresINSA/24h-android-app/issues/34#issuecomment-92460677>
> .
>


-- 
Léo MARTINEZ

**Comment by remipichon** [comment]
le 3030 ? Noway ...

**Comment by thelittle** [comment]
Et pourtant si.
Du coup ça soulève un problème intéressant. Il serait peut-être plus judicieux de servir les JSON sur le port 80. Par contre, cela implique une migration d'Assomaker sur un autre serveur... Il faut qu'on y réfléchisse, mais ça peut être une solution.

**Comment by remipichon** [comment]
Yep, je pense qu'on peut partir du principe que les users seront sur des réseaux mobiles ou les ports sont ouverts. Les gens ferment pas trop leur port chez eux en Wifi... 
Je pense qu'on peut rester sur le 3030, peut etre fournir un backup en get sur le 80 avec une URL dégueulasse qui sera utilisé si timeout des get sur 3030. 
On verra si on a du temps

**Comment by remipichon** [comment]
il reste à gerer : 

les erreurs de connectivité internet (juste un crouton demandant d'activer internet)

les feebacks de l'appel /version (peanuts....)

**Comment by remipichon** [comment]
mettre en place un coutron avec un bouton reassayer si erreur
