### ISSUE TITLE
fix issues after release 0.1

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#46]
* afficher les photos a partir de l'indice 1 dans le carousel

**Comment by remipichon** [comment]
ne pas envoyer la main_picture dans pictures (coté backend)

**Comment by remipichon** [comment]
A l'occasion tu pourras faire ca ? Pas besoin de me prévenir, l'appli n'est pas impactée

**Comment by thelittle** [comment]
En prod.
