### ISSUE TITLE
partie concert

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#47]
Backend : 
possibilité de mettre un ordre

Mobile : 
le premier de chaque soir occupe une grande card
un tab par soir

**Comment by thelittle** [comment]
Yop ! Je m'occupe du backend ce weekend (je ferai le numéro de version côté backend en même temps). ;)

**Comment by remipichon** [comment]
Lucas, le backend est pret et NightDetailFragment n'attend que toi !

**Comment by LucasBettarel** [comment]
Parfait on y va!



Lucas Bettarel

2015-04-24 3:39 GMT+08:00 Remi Pichon <notifications@github.com>:

**Comment by remipichon** [comment]
Le backend est de nouveau pret, ou en es tu de cette tache ?

**Comment by LucasBettarel** [comment]
@remipichon 
pour la 0.9, ce qui depend de moi, il me reste : 
- afficher icone scene sur liste
- afficher texte scene sur detail

la ou j'attend d'autres resolutions d'issues, avant 1.0
- backend artiste a mettre a jour
- tab par day
- next schedule text->horaire a 19h
- tri par importance

puis close :)

**Comment by remipichon** [comment]
- backend artiste a mettre a jour OK
- tab par day OK
- next schedule text->horaire a 19h : je comprends pas, que demandes tu ?
- tri par importance : si tu veux le faire pour ta cultulre c'est pas compliqué, je peux t'expliquer

**Comment by LucasBettarel** [comment]
-> il s'agit de l'issue #167
a la place de la grille des horaire, j'ai mis (pour l'instant un textView
en dur) pour dire que les horaires seront visibles le jour du concert a 19h.
il faudrait que dynamiquement dans le schedule adapter on ait un event le
soir du concert a 19h pour qu'apparaisse les horaires (pour l'instant pas
remplis sur le backend).

-> je peux me dermerder je pense, il faut juste redefinir la "position de
l'artiste" dans le backend -> du type : ordre d'importance 1 à 5 (si
plusieurs au meme-> ordre alphabetique).
Je m'occuperais de cette fonction en fin de semaine, pour la 1.0



Lucas Bettarel

**Comment by remipichon** [comment]
-> 
Tu t'embetes avec ton textView. Si tu utilises un TextView a la place du ScheduleAdapter apposé à un GridView il faut que tu descendes le métier gérant les schedules de abstract DetailFragment a DayDetailFragment. L'avantage de garder la généricité est une force d'unicité dans le code qui se vera coté design. Enfin bref, tant que tu t'arranges pour ne pas faire de regression coté jour ca passera
Pour l'evenement il n'y a pas besoin. L'histoire des horaires affichés à 19h est géré par le backend. Coté mobile tu dois juste afficher le label "non dispo" si schedule == null ou afficher le schedule. Ok ?

->
la position t'es deja envoyé par le backend, et j'ai ajouté le code qu'il faut dans le model (nightResource.position).
Le tri se fait à la reception, une fois pour toujours. Regarde DataBackendServiceImpl.getResourcesAsyncFromBackend L95

**Comment by remipichon** [comment]
J'ai adapté ton boulot pour matcher ce qui est présent coté journée. 

Il te reste 
-afficher icone scene sur liste

il me reste
-tab par day
-next schedule text->horaire a 19h

**Comment by LucasBettarel** [comment]
Ok cool, si le trigger est gere par le backend no probleme.
Oui j'ai bien vu les heritage entre les details jour et nuit et le lien
avec le fragment. Je vais degager le text view et simplement afficher le
meme contenu text a la place de schedule = null.

Je fini ca ce soir donc :)



Lucas Bettarel

2015-05-05 7:03 GMT+08:00 Remi Pichon <notifications@github.com>:

**Comment by remipichon** [comment]
Normalement tu n'as plus besoin de passer de temps la dessus. Mon bricolage devrait

**Comment by LucasBettarel** [comment]
Pour que ca marche oui, on verra si j'ai le temps d'embellir un peu quand meme.
