### ISSUE TITLE
Animation de chargement page accueil + images

### ISSUE THREAD

**Issue by LucasBettarel** [24HeuresINSA/24h-android-app#56]

**Comment by remipichon** [comment]
Splash screen, je l'ai fais en code. C'est la mainActivity qui sera renommé SplashActivity une fois que je l'aurai allégée au maximum. Il reste le layout a faire, de prefere tres light, sans animations. L'idée est que la splashscreen ne consomme aucunes ressources au démarrage

**Comment by remipichon** [comment]
Pas le temps pour la deuxieme MEP
