### ISSUE TITLE
effacer autres icones de l'action bar pendant une recherche

### ISSUE THREAD

**Issue by LucasBettarel** [24HeuresINSA/24h-android-app#57]
je sais pas encore comment on fait ca mais on va voir

**Comment by remipichon** [comment]
C'est deja le cas, testé avec un 4.4 et un 5.0

**Comment by remipichon** [comment]
Tu peux la fermer si tu reproduis pas le bug ?

**Comment by LucasBettarel** [comment]
Il y est encore. Je t'envoie un screen des que j'ai internet sur le tel.



Lucas Bettarel

2015-04-15 1:43 GMT+08:00 Remi Pichon <notifications@github.com>:

**Comment by LucasBettarel** [comment]
![2015-04-15 13 54 26](https://cloud.githubusercontent.com/assets/11612891/7163548/3ca378ec-e3cd-11e4-9854-bfdef5aefc8c.png)

voila ce que ca donne chez moi.
De plus, je tombe sur la liste au depart, avec l'onglet a map, c'est normal?

**Comment by LucasBettarel** [comment]
une autre ce que ca fait de temps en temps

![2015-04-14 23 33 16](https://cloud.githubusercontent.com/assets/11612891/7163589/74d96802-e3cd-11e4-8141-6213f38ad08e.png)

**Comment by remipichon** [comment]
Est ce qu'il n’apparaît que lorsque le clavier est affichée? Est ce qu'il apparaît à chaque fois que le clavier est affiché ?

**Comment by LucasBettarel** [comment]
a chaque fois pour moi



Lucas Bettarel

**Comment by LucasBettarel** [comment]
ah et ça pas plus en icon_setting maintenant, ca decale simplement l'icone sur la droite

**Comment by remipichon** [comment]
"ah et ça pas plus en icon_setting maintenant, ca decale simplement l'icone sur la droite" pas compris

A chaque fois, chaque fois que le clavier est affiché ?

**Comment by LucasBettarel** [comment]
pardon, je voulais dire que mon premier screenshot n'est plus d'actualite
(trois points au lieu de l'icone coeur)

c'est comme ça que le clavier soit affiché ou pas, å chaque fois. (de toute
facon le clavier s'affiche automatiquement)



Lucas Bettarel

2015-04-16 0:28 GMT+08:00 Remi Pichon <notifications@github.com>:

**Comment by remipichon** [comment]
Etrange, ca doit venir de Lollipop car pour la recherche j'utilise un widget fournit tout pret tout beau, je ne maitrise pas ce qui est masqué ou non

**Comment by remipichon** [comment]
Je teste ca ce soir

**Comment by LucasBettarel** [comment]
j'avais essayé d'y remedier mais sans succes. Dis moi si tu fais mieux.



Lucas Bettarel

2015-04-16 0:39 GMT+08:00 Remi Pichon <notifications@github.com>:

**Comment by remipichon** [comment]
Je ne reproduis pas ce bug sur mon Lollipop virtualisé, j'essaie demain avec des devices du boulot

**Comment by remipichon** [comment]
J'ai testé sur un Nexus5 en 5.1, pas de soucis. En quelle version es tu ?

**Comment by LucasBettarel** [comment]
5.0.1


si vraiment c'est que mon telephone je dirais tant mieux mais c'est
bizarre...



Lucas Bettarel

2015-04-17 20:31 GMT+08:00 Remi Pichon <notifications@github.com>:

**Comment by remipichon** [comment]
Yep, 5.0.x est bien buguée, elle nous a apporté pas mal de soucis au boulot. 

Disons que c'est la faute d'Android puisque de toute facon je peux pas faire grande chose pour regler ce soucis. 

Est ce que le bouton favorites est cliquable ? Si oui, que se passe t'il ?

**Comment by LucasBettarel** [comment]
il repond normalement

par contre j'ai des stop unexpectedly de temps en temps, je sais pas
pourquoi. quand je clique trop vite sur lq map ou la liste des fois, tu as
deja eu?




Lucas Bettarel

**Comment by remipichon** [comment]
Bon, s'il fait pas crasher c'est bon point, je ferme la issue en disant que la faute est à la version 5.0.1.

**Comment by remipichon** [comment]
Pour les unexpectedly, lorsque tu essaies de switcher de maps a list trop rapidement ?
