### ISSUE TITLE
organisation display schedules in detail

### ISSUE THREAD

**Issue by LucasBettarel** [24HeuresINSA/24h-android-app#59]

**Comment by remipichon** [comment]
Pourquoi ? Vu ce qu'il nous reste à faire d'urgent je descope ca. Ré-ouvre si c'est pas juste de la mise en page des schedules

**Comment by LucasBettarel** [comment]
C'est ce qui rend le mieux a mon avis, en considerant que l'on peut pas faire trois colones (petites devices) et qu'on a parfois trois jours differents pour une meme activite. Dans ce dernier cas precis la solution a plusieurs colone rend moche, du coup une seule colonne pour tout le monde...

**Comment by remipichon** [comment]
Mais ca prend pas trop de place ?

**Comment by LucasBettarel** [comment]
90% il n'y a que un ou deux schedule, donc pas trop non. Je les ai serres
pour que la liste soit compacte.
Tu me diras ce que tu en penses, moi ca me gene pas visuellement



Lucas Bettarel

2015-04-27 17:41 GMT+08:00 Remi Pichon <notifications@github.com>:

**Comment by remipichon** [comment]
Est ce que tu as essayé avec Stand Accueil ? C'est la resource la plus relou niveau horaire. Si ca passe meme avec celle là, tout baigne. 

Pense également à tester sur des resolutions plus petites que celle de ton N4 avec Genymotion (tu n'auras pas la Maps d'affichée en revanche)

**Comment by LucasBettarel** [comment]
J'ai que 2 horaires sur stand accueil...

**Comment by remipichon** [comment]
closed ?
