### ISSUE TITLE
icone search

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#63]
sa quaité est pas ouf, il pixelise par rapport au autre

**Comment by LucasBettarel** [comment]
drawable/ic_action_search.png?
c;est bizarre ca le fait pas sur mon nx4. ok je remplace l'icone du drawable par les differentes version standards (hdpi,...)

**Comment by remipichon** [comment]
En fait il pixelise pas vraiment, il y a juste un effet blur que n'ont pas tous les autres icones

**Comment by LucasBettarel** [comment]
tu peux m'envoyer un screenshot?
j'ai pas du tout ca moi, elle rend tres bien : c'est une icone standard android decline dans toutes les tailles dans les drawables, j'y ai pas touché!

**Comment by remipichon** [comment]
SearchView ne permet pas de redefinir l'icone utilisé. Le rendu était bon sur un 5.x mais pas sur un 4.4.4. J'ai utilisé un trick pour pouvoir utiliser un de nos icones, le rendu est bon sur 3 resolutions différentes. Je ferme tant pour le moment, à voir si le rendu est bon de partout
