### ISSUE TITLE
icone favorite

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#64]
il est pas beau ! (j'avais mi celui en vitesse sans choisir)

**Comment by LucasBettarel** [comment]
il faut virer les ressources non utilis'ees. quand tu as merge ma premiere request, tu as laisse tout ce que j'avais supprime.
Ou c'est la nouvelle icon favorite que tu aimes pas? Dans le code c'est la nouvelle qui est assignee

**Comment by remipichon** [comment]
les merges ne sont pas à fait à la main, c'est Git qui s'en charge. Lors de clean de fichiers, il faut bien commiter la suppression, il faut prevenir le repo que des fichiers ont été supprimé. Le versionning fonctionne par difference et pas par copie de repo. 

Je trouve l'icone présent sur la master funky pouet pouet, il est pas du tout flat/material. Le trait de l'icone n'est pas regulier. 

Je ferai une reunion design avec toute l'equipe apres la troisieme MEP pour parler de ce genre de point qui ne prenne pas beaucoup de temps de dev

**Comment by LucasBettarel** [comment]
j'ai mis celui d'android lollipop pour check du coup
le uncheck ca rend pas top ce que j'ai fait. je le changerais sur photoshop bientot

**Comment by remipichon** [comment]
Un peu plus gros, histoire d'optimiser l'espace et je pense que ca ira. Qu'en penses tu
