### ISSUE TITLE
reflexion

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#67]
"Dans le menu : j'ai vu que vous avez mis des couleurs sur les logos dans les différentes catégories. Est-ce qu'il est possible de faire apparaître ces différentes couleurs 
sur les logos du menu?"

"Dans le menu : Il y a une partie ""TOUT LE TEMPS"". Je trouve ça bizarre de mettre les paramètres là-dedans. En fait je pense qu'il faudrait changer le titre tout simplement,
parce qu'en plus ça fait un peu ""enfantin"" (je trouve). Pourquoi pas ""Liens pratiques"" par exemple"

"Dans les fiches descriptives de chaque anim, quand il y a plus de deux plages horaires, je trouve que l'enchaînement n'est pas cohérent. Ca fait gauche puis droite puis 
à la ligne et re gauche droite. JE trouverai ça plus logique de faire les horaires du samedi à gauche et les horaires du dimanche à droite"

**Comment by LucasBettarel** [comment]
les couleurs sur les icones de menu pourquoi pas. augmenter leurs taille dans ce cas.

Dans parametres il y a aura quoi concretement? Sinon j'enleverais tout simplement le titre, la barre suffit pout demarquer cette partie des deux autres.

Je m'occupe de mettre les colonnes d'horraires par jour

**Comment by remipichon** [comment]
Nous parlerons de ces points lors d'une reunion apres la 3eme MEP. Pas la peine de commencer ces taches là tout de suite

* j'ai mi en place hier les couleurs de marker pour la Maps et ajouter les couleurs dans le navigation drawer me semble d'autant plus pertinent

* a voir ce que ca donne sans label pour la partie "tout le temps", les reglages n'ont rien pour le moment

* si besoin, ce sera dans le comparator
https://github.com/24HeuresINSA/24h-android-app/blob/master/app/src/main/java/com/insalyon/les24heures/utils/ScheduleComparator.java
et dans l'enum
https://github.com/24HeuresINSA/24h-android-app/blob/master/app/src/main/java/com/insalyon/les24heures/utils/Day.java
qu'il faudra toucher quelque chose

**Comment by LucasBettarel** [comment]
check avec les icones colores ce que tu en penses

**Comment by remipichon** [comment]
J'aime bien les icones colorés dans le navigation drawer, on garde l'ancien visu sous le coude au cas ou

**Comment by remipichon** [comment]
conserver la resourceSelected en passant de list à maps

centrer le title sur le detail header en mode collaspe expand par rapport au mode visible

**Comment by remipichon** [comment]
only next schedules in list
