### ISSUE TITLE
display selected category in drawer [blue]

### ISSUE THREAD

**Issue by LucasBettarel** [24HeuresINSA/24h-android-app#68]

**Comment by remipichon** [comment]
Tu veux changer la couleur de le selected categoy ? 

Il faut redefinir l'attribut activatedBackgroundIndicator utilisé L76 de styles.xml

**Comment by LucasBettarel** [comment]
Pour le fond c'est ok, en revanche pour le label et l'icon je patauge un peu plus. D'apres mes recherches, il faudrait s'en occuper en java dans un navdrawer_adapter, mes hormis le category adapter (ou ca marche pas des masses) j'ai rien trouvé de comparable dans les java files.
Faut il le creer pour avoir acces a des fonctions qui impactent tout le nav drawer?

cf ce gars la : https://blog.samsaodev.com/how-to-customise-the-text-appearance-of-a-selected-section-in-a-navigation-drawer/

**Comment by remipichon** [comment]
Toutes les propriétés des layouts peuvent etre modifié par des drawables tel que activatedBackgroundIndicator en fonction de l'état de l'élement (activated, selected, enabled....). Ainsi que ce soit le background ou la couleur du label ca doit pouvoir se faire en XML pure. Pour l'icone c'est un peu plus tricky, tu pourrais effectivement le faire en Java dans le getView du CategoryAdapter mais il y a peut etre moyen de le faire en XML également. Si tu créé un filtre de couleur bleu sur l'icone pour changer son apparence sans changer le fichier, ensuite tu appliques ce filtre ou non en fonction de l'état selected ou non. 
Vois tu l'idée ?

**Comment by LucasBettarel** [comment]
a priori non. Apres plusieurs test infructueux, il n'y que le background qu'on peut customiser avec un selector drawable. tu pourras essayer mais j'en reviens au code a chaque fois.
de toute façon pour l'icone il faudra faire un onselectedItem donc autant gerer le texte en meme temps.

category adapter ne gere que les 4 premieres icones, j'aimerais pouvoir acceder a toutes les icones du drawer

pour le filtre ça fait degeu car la couleur de base est gris foncé, en multiply ça va rien rendre.

**Comment by remipichon** [comment]
Pour la couleur du label, est ce que tu as ajouté un nouveau drawable sur le TextView lui meme ? Si tu appliques un font color sur l'item category qui est un linear layout qui contient le imageView et le TextView, le font color ne sera pas distribué sur le TextView. Ca ne fonctionne pas comme en CSS. En revanche tu peux faire de l'heritage entre style. 
Si tu appliques un style au TextView qui hérite du style que tu appliques au LinearLayout sur lequel tu fais deja le boulot du background, ca devrait fonctionner. 

Je ne comprends pas ce que tu dis pour le onSelectedItem

CategoryAdapter gere tous les icones de toutes les categories, non ?

C'est vrai qu'à partir du gris le filtre risque d'etre compliqué à designer. Si tu veux effectuer le changement d'icone en code, il faut recuperer l'item selected dans le getView de CategoryAdapter et effectuer convertView.setImageResource. Pour recuperer l'item selected il faut regarder du coté de convertView.isSelected ou quelque chose de ce gout là.

**Comment by LucasBettarel** [comment]
1 - J'ai un crash quand je mets un drawable sur android:textcolor du textview
2 - si je mets le drawable sur android:background du textview : rien ne se passe avec le selector qui gere les android:color

je disais que pour changer l'icone d'un selectedItem dans le drawer, vu que c'est pas possible en xml apparament, il faudra faire une methode onSelectedItem dans une sorte de draweradapter, qui fait icon.setimageview("icone bleu") et en meme temps textview.setcolor("bleu'), si tu vois l'idée.

Justement. category adapter ne gere que les categories, mais je veux pouvoir faire ca aussi sur les pages statiques, pour pouvoir voir sur quelle page on est lorsqu'on tire le drawer depuis une page statique.

je comprends pour les icones de category, si on peut etendre cette technique a tout le drawer c'est top

**Comment by remipichon** [comment]
Je vais regarder pour cette histoire de drawable pour le background et la font color 

J'avais oublié qu'il y a avait d'autre item que les categories dans le navigation drawer. C'est pour cela que c'est mieux si on arrive à faire tout avec les drawable et les différents états. Ainsi c'est Android qui se demerde pour switcher les états et appliquer les bon jeu de couleurs.

**Comment by remipichon** [comment]
J'avais deja mi en place le métier necessaire à ce que tu dis, dans BaseDynamicDataActivity

@OnClick(R.id.navigation_drawer_artists)
    public void onClickArtist(View v) {
        clearDrawerChoices();
        v.setActivated(true);
        drawerLayout.closeDrawer();
        nextActivity = NightActivity.class;

    }

    private void clearDrawerChoices() {
        clearDrawerChoices(true);
    }

    private void clearDrawerChoices(boolean clearList) {
        if (clearList) {
            categoriesList.clearChoices();
            categoriesList.requestLayout();
        }
        artistButton.setActivated(false);
    }

**Comment by remipichon** [comment]
Je fais  #74 au plus vite afin que tu puisses attaquer les pages statiques et finir cette issue

**Comment by LucasBettarel** [comment]
c'est vraiment con mais celui la faut que je te demande en live... si tu veux me marquer un petit point hangout...

Tu as fait une base activity ou on peut recuperer les isselected des item du drawer statiques, pour les dynamic, ca se passe dans category adapter.

Dans base activity en revanche, tu n'a pas specifies de fonction qui permettent de recuperer facilement les items du drawer (equivalent de viewholder holder dans l'adapter, notamment). Du coup, dois-je faire 2 fois la meme fonction pour statique et dynamic? auquel cas comment recuperer ces elements sans foutre le bordel dans ton joli code?

l'idee est au final la suivante, c'est tres simple mais bon:
- on click sur un element du drawer
- recupere id/position + view
- si active, 
       change img de icon (bleu)
       change couleur texte (bleu)
 sinon
       change img de icon (gris)
       change couleur texte (gris)
voila... la partie qui me pose probleme est donc la recuperation des views/position

Merci bien!

**Comment by remipichon** [comment]
Tout le monde hérite de BaseActivity, cette abstract (et elle seule) s'occupe du Navigation Drawer. Tout le métier le concernant doivent se trouver dans cette classe. Tu dois donc ajouter une méthode dans Base Activity et l'utiliser depuis BaseActivity pour que les 3 activities puissent avoir le fonctionnel du navigation drawer. 

Pour le onClick sur les elements du drawer, il y en a 2 sortes : les onItemClick du categoryAdapter et les onClick des autres items. Il faut bien penser au deux. Il va aussi falloir traiter de deux manieres le switch d'icone. Pour les category ca se fera dans le getView de CategoryAdapter. Pour les autres items ca pourra se faire dans une méthode de BaseActivity. 
Tu peux te contenter de recuperer juste le view du onClick et effectuer du traitement sur cette vue, c'est une bonne idée de recuperer la position, ou quelque chose de parcelable qui représente l'item selected. En effet, il faut etre capable de restaurer l'item selected au changement d'activity (puisque tout est detruit puis reconstruit) 

Il y a donc un peu de métier derriere cette issue. Lucas a finit le backend pour les artistes, tu peux donc commencer la partie concert. Elle aussi a pas mal de métier et est bien plus prioritaire. Peux tu commencer par ca ? Nous verons plus tard pour cette histoire d'item selected dans le navigation drawer. 

Ok pour toi ?

On peut se faire un point demain après midi si tu as des questions.

**Comment by LucasBettarel** [comment]
non pas fini.
toujours le probleme pour la journee, comme je disais
on verra plus tard

**Comment by remipichon** [comment]
J'ai mergé #130

**Comment by LucasBettarel** [comment]
Bien vu.
Tu pourras m'expliquer comment tu as fais (pour trouver ce qu'il fallait
faire, ya des methodes que je sais pas utiliser ici!) ? pour ma culture
personnelle... merci!



Lucas Bettarel

2015-04-28 0:33 GMT+08:00 Remi Pichon <notifications@github.com>:

**Comment by remipichon** [comment]
Le CategoryDrawer a un listener d'event. Au onClick de lance l'evenement categorySelected afin que MapsFragment et ListFragment puissent mettre à jour leur content en fonction. 
Sur ce meme onClick je stocke dans positionCategorySelected la position de la category sélectionnée (logique hein). 
Le categoryAdapter compare pour chaque item la position et positionCategorySelected pour savoir quoi faire.
La ou ca ne fonctionnait pas c'est qu'effectivement le NavigationDrawer n'est systmatiquement reconstruit. Ainsi, au onClick du DrawerListener j'appelle categoryAdapter.notifyDateSetChanged ce qui permet de provoquer le redraw des categories. 

Ajoute a ca un peu de savante tambouille pour stocker la positionCategorySelected et la restaurer au besoin ainsi que la passer comme il faut en parametres
