### ISSUE TITLE
Descriptions pour le PlayStore

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#71]
Demander à la ComCom

Description courte : 80 caracteres

Description complete : 4000 caracteres

Elements importants : 

* les dates
* du charisme
* toutes les anims journée avec horaire
* tous les concerts avec les horaires divulgués le soir meme

**Comment by LeaLeBaron** [comment]
Retrouve désormais le festival des 24 Heures de l'INSA dans ton mobile.

Les 22, 23 et 24 mai 2015, le festival des 24 Heures de l'INSA revient sur le campus de la Doua, à Villeurbanne, avec toutes ses animations pour petits et grands, ses courses folles, et ses concerts.
Que tu y viennes pour faire une balade à poney, acclamer les coureurs ou danser jusqu'au bout de la nuit, tu peux désormais disposer à portée de main de toutes les informations du plus grand festival étudiant de France.

Retrouve ainsi l'emplacement et les horaires de toutes les animations organisées en journée. 
Viens découvrir la programmation de l'édition 2015 ou réécouter tes artistes préférés en attendant de connaître leur horaire de passage sur scène.
Accède à toutes les infos pratiques du festival (transports en commun, billetterie, lieux utiles, etc...)

Sélectionne les animations auxquelles tu veux assister, et compose la liste de tes artistes favoris afin de profiter pleinement des 24 Heures de l'INSA et de vivre un festival sur-mesure !

**Comment by remipichon** [comment]
Top top !




--
Remi Pichon
