### ISSUE TITLE
nouveau theme de couleur pour le everywhere

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#83]
L'ennui c'est que TicketsFragment est gérer par StaticDataActivy, on peut pas juste creer un troisieme theme à partir de "DayActionBarTheme" ou "NightActionBarTheme"

deux choix : 
Soit : tu crées un troisieme theme EverytimeActionBarTheme qui est appliqué à l'activity dans le manifeste et on surcharge le theme de l'activy lorsqu'on est sur TicketsFragment

Soit : je deplace la gestion du TicketsFragment dans NightActivity

Je suis plus pour la premiere option si elle fonctionne, car la deuxième alourdirait pas mal les deux classes deja bien remplie

**Comment by LucasBettarel** [comment]
On ne peut changer le theme en java que sur le on Create Activity.
Si on passe des autres pages statiques a la billeterie on pourra pas changer le theme.

La seconde solution est malheureusement la seule qui semble marcher (au detriment de mon bordel de blue selected drawer ha ha ). Je te laisse le faire ou bien?

**Comment by remipichon** [comment]
ca parait crédible de ne pas pouvoir changer le theme autre que dans le onCreate. Je m'occupe de migrer le TicketFragment dans NightActivity. 

Est ce que tu peux créer le theme pour les pages statiques et l'appliquer dans le manifest pour StaticDataActivity ? Et lorsque j'aurais le temps je changerai TicketFragment d'acivity

**Comment by LucasBettarel** [comment]
ok cool merci,

C'ets fait



Lucas Bettarel

**Comment by remipichon** [comment]
C'est fait ? Deja commité ?




--
Remi Pichon

**Comment by LucasBettarel** [comment]
je prepare le merge sur master.



Lucas Bettarel

**Comment by remipichon** [comment]
excellent




--
Remi Pichon
