### ISSUE TITLE
artiste : horaire 

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#92]
envoyer la clef à null si pas d'horaire

**Comment by LucasBettarel** [comment]
ajouter aussi la scene dans assomaker, pour l'instant ca y est pas

**Comment by thelittle** [comment]
Pour la scène, elle y est, c'est la clé "stage".

**Comment by thelittle** [comment]
En prod.

**Comment by remipichon** [comment]
Je les ré-ouvre pour que je la prenne en compte
