### ISSUE TITLE
detail : partager sur les reseaux sociaux (via appli native)

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#96]
il n'y a pas de mockup pour, ni aucunes ressources, qui peuvent demandé à Lucas

Depuis un Detail (Day or Night) en état "anchored" ou "expanded", dans l'action bar il y un bouton pour partager la ressource.

Le partage sur Facebook et Twitter répond au UC suivantes
UC 1.6.4
UC 1.6.6
en utilisant l'application native des users. On s'embete pas à recuperer leurs credentials ou a utiliser les API. Il faut 'juste' créer l'intent qui va bien pour taper les applis Twitter et Fb

**Comment by lbillon** [comment]
Je vais m'attaquer à ça : )

Il me faudrait cependant : 
* Pour @thelittle ou @LucasBettarel  sur le site 24heures.org , une ancre html pour chaque animation, pour que quand j'accède à 24heures.org/animations/#10 ,  ouvre la page et scrolle jusqu'à l'animation 10 et que ça la mette un peu en suibrillance (propriété CSS target)

Un exemple : http://aarontgrogg.com/blog/2012/05/18/pure-css-highlight-for-link-target/

**Comment by lbillon** [comment]
@remipichon comme je te l'ai dit hier, je suis un peu perdu dans l'archi, on voit ça ensemble à l'occasion ; )

**Comment by lbillon** [comment]
Le frontend est implémenté, je ferme.
On rouvrira une autre si on veut du plus sexy.
