### ISSUE TITLE
Alerting - live update : backend

### ISSUE THREAD

**Issue by remipichon** [24HeuresINSA/24h-android-app#99]
99.1 : En tant qu'orga, je peux ajouter/supprimer un nouveau message string de 140 char 

99.2 : En tant que backend, je peux fournir la liste des messages

**Comment by remipichon** [comment]
99.2 : un nouveau verbe qui envoie un JSON
[
{
date : timestamp,
content : String
},....


]

**Comment by lbillon** [comment]
Hello, pour l'instant on utilise un bête json,
l'url est liveUpdates
il faut que l'on discute pour savoir ce que l'on veut comme fonctionnalités

**Comment by remipichon** [comment]
Pour le fonctionnel :
+ UC 99.3 : en tant que festivalier je veux recuperer les précédents messages au lancement de l'application (une notif propose d'aller voir dans la page LiveUpdate pour voir les nouveaux messages)
+ UC 99.4 : en tant que festivalier je veux recevoir les messages en temps reel (le nouveau message est ajouté à la page LiveUpdate et l'utilisateur recoit une notification)
+ UC 99.1 : en tant qu'orga je peux envoyer un nouveau message aux utilisateurs de l'application (via assomaker)


Est ce fonctionnel te semble bien ?

**Comment by remipichon** [comment]
Techniquement : 

A part l'histoire du port 3030, le principe d'avoir nos données servies statiquement me plait bien. La 99.3 me parait bien avancé avec la merge request #105.

Assomaker propose une interface toute bete pour envoyer un message (reflechir sur le max de char) qui POST sur le Node qui gere le polling sur le GCM. 
Au démarrage de l'appli, elle se register auprès du Node qui stocke tous les GCM registerId. 

Comme je vois les choses, le NodeJs stocke les registerId et se charge du pooling à la reception d'un POST venant de assomaker. 
Assomaker stocke les messages et propose une interface UI pour faire le CRUD. Si tu veux tout faire en NodeJs fait toi plaisir !

**Comment by lbillon** [comment]
See #131
